language: node_js
node_js:
- '0.12'
before_install: npm install -g grunt-cli
env:
  global:
  - secure: VweZFMRKS2vmkhSqGD+lmh5T1mTIgUHThyBSs4GrbvmqDXSfJsd072TZOQJNgfct15ldwH02v1civeNWJie7qBT3u//uKUDJo6BZ9ydUIUUs/4FYdm/fJY3k9nV4eoPMUWJHfcMSLnpcnD3eOpRVAzIYt9zVfGpo8yIemF0HNio=
  - secure: iNlrBA5NB+DtY3wuFA34ThiZayswnXBdf/4vCQyAz6NJYT7IUx8CjVwAb1UOmb9UfFppcnZOSLpzboMuaWsVeKSsPuppGgiWDSU0whoBvpNC9ImD4YO7ZRpeZ25WsAOCp6lz/ypbicu0lSwvmCguVSus8F9EPQUWuEp0oHw+ZMs=
  - secure: ccwwpdxdUpufkFqQUWGdCQAF1TI+Nx1TDVHCIaRM8IdoBU0wc6XD7HEEqq9gNeB3GG5tvPYzwLfj9ARpEiO+KZObLCcaEI5ZKSXPNADzL05fmL8uUDQENR7q+K1iSe5lpE+iBWH1/SHUxUbIzIY1qlaA9+qoKZzzai6JQXEKdzE=
deploy:
  on:
    branch:
    - webstore
    - webstore_staging