language: node_js
node_js:
- "6"
before_install:
- npm install -g grunt-cli

# ENVIRONMENT VARIABLES: CHROME WEBSTORE CREDENTIALS
env:
  global:
  - secure: VweZFMRKS2vmkhSqGD+lmh5T1mTIgUHThyBSs4GrbvmqDXSfJsd072TZOQJNgfct15ldwH02v1civeNWJie7qBT3u//uKUDJo6BZ9ydUIUUs/4FYdm/fJY3k9nV4eoPMUWJHfcMSLnpcnD3eOpRVAzIYt9zVfGpo8yIemF0HNio=
  - secure: iNlrBA5NB+DtY3wuFA34ThiZayswnXBdf/4vCQyAz6NJYT7IUx8CjVwAb1UOmb9UfFppcnZOSLpzboMuaWsVeKSsPuppGgiWDSU0whoBvpNC9ImD4YO7ZRpeZ25WsAOCp6lz/ypbicu0lSwvmCguVSus8F9EPQUWuEp0oHw+ZMs=
  - secure: ccwwpdxdUpufkFqQUWGdCQAF1TI+Nx1TDVHCIaRM8IdoBU0wc6XD7HEEqq9gNeB3GG5tvPYzwLfj9ARpEiO+KZObLCcaEI5ZKSXPNADzL05fmL8uUDQENR7q+K1iSe5lpE+iBWH1/SHUxUbIzIY1qlaA9+qoKZzzai6JQXEKdzE=

# BUILD WEBSTORE PACKAGE
before_script:
- npm test

# DEPLOY TO CHROME WEBSTORE
script:
- if [ $TRAVIS_BRANCH == 'webstore' ]; then grunt build; fi
- if [ $TRAVIS_BRANCH == 'webstore' ] && [ $TRAVIS_PULL_REQUEST == "false" ]; then grunt webstore; fi

# DEPLOY TO GITHUB RELEASES
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://dragonjet:$GITHUB_API_KEY@github.com/KC3Kai/KC3Kai --tags
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_API_KEY
  file: build/releases.zip
  on:
    tags: false
    branch: dev-crx
    condition: $TRAVIS_PULL_REQUEST == "false"

# BUILD NOTIFICATION FOR GITTER
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e8964a721dd35fd96e46
    on_success: change
    on_failure: always
    on_start: never